menu:
  Embedded: embedded/
  DevTools: tools/
  IoT: iot/
  About: https://github.com/m2cloud/
  Docs: doc/


doc_sidebar:
  Getting Started:
    Overview: index.html
    Setup: setup.html
    Configuration: configuration.html
    Commands: commands.html
    Migration: migration.html
  Basic Usage:
    Writing: writing.html
    Generating: generating.html
    Tag Plugins: tag-plugins.html
    Server: server.html
    Deployment: deployment.html
  Customization:
    Permalinks: permalinks.html
    Themes: themes.html
    Variables: variables.html
    Pagination: pagination.html
    Helpers: helpers.html
    i18n: i18n.html
  Advanced:
    Models: models.html
    Events: events.html
    Plugins: plugins.html
  Miscellaneous:
    Troubleshooting: troubleshooting.html
    Contributing: contributing.html

embedded_sidebar:
  Getting Started:
    M0: index.html
    M3: setup.html

tools_sidebar:
  Getting Started:
    M0: index.html
    M3: setup.html

iot_sidebar:
  Getting Started:
    M0: index.html
    M3: setup.html

google_analytics: UA-4910098-7